### ISSUE TITLE
Documentation!

### ISSUE THREAD

**Issue by rwjblue** [emberjs/ember-render-modifiers#2]
- [x] API docs
  - [x] `did-insert`
  - [x] `did-update`
  - [x] `will-destroy`
- [ ] General usage guides
  - [x] Copy usage examples from emberjs/rfcs#415 (#3)
  - [ ] Identify common example scenarios, document how to handle them...

**Comment by rwjblue** [comment]
@knownasilya - I haven't dug into it much yet, but yeah that sounds like it might make the whole process a bit nicer.

**Comment by GavinJoyce** [comment]
✋ I'll take this on

**Comment by GavinJoyce** [comment]
@rwjblue does the API docs checkboxes above refer to creating docs in the modifier source files or somewhere else?

**Comment by rwjblue** [comment]
@GavinJoyce - Ya, I was thinking that inline docs (plus something _like_ `documentation` package to generate an `API.md`) would work well.

**Comment by GavinJoyce** [comment]
👍 thanks

**Comment by tomdale** [comment]
@GavinJoyce Where are we at on this?

**Comment by GavinJoyce** [comment]
@tomdale Here's a [PR](https://github.com/emberjs/ember-render-modifiers/pull/8) which adds some API docs for `{{did-insert}}`, `{{did-update}}` and `{{will-destroy}}`

**Comment by lupestro** [comment]
And the docs should mention the thing I stumbled over recently - when you use FastBoot, you will get calls to the actions of `{{did-insert}}` and `{{will-destroy}}` with `element === null`. Since I'm usually adding focus listeners to focusable elements within a contextual block or some such thing, in my code, I was able to just `if` around all that safely - it won't matter in the fastboot snapshot - but it helps to anticipate it.

**Comment by rwjblue** [comment]
@lupestro - This is a bug, and should be fixed in Ember (and the polyfill). Likely the same as https://github.com/emberjs/ember.js/issues/17949.
